# Generated by Django 4.2 on 2023-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
