# Generated by Django 4.2 on 2023-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_car_phot_4_car_car_photo_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
